### ISSUE TITLE
Use constants for SupportedProtocols

### ISSUE THREAD

**Issue by CaptainMesomorph** [iov42/core-sdk-dotnet#3]
This is a request rather than an issue.

Would it be possible to define supported protocols as constants rather than "static readonly"? This would allow them to be used in switch expressions. For instance:

```
        public const string Sha256WithRsa = "SHA256WithRSA";
        public const string Sha256WithEcdsa = "SHA256WithECDSA";
```

**Comment by markiov42** [comment]
This is an interesting one.

The reason I picked the use of static readonly is that this is the perceived recommended approach for libraries. The reason being that if the underlying value changed then it would require a recompile of all clients that use it as opposed to just updating the library.

Having said that, the expected usage of this library (especially in it's current source code form) is likely to require clients to recompile anyway so it becomes less of an issue. And also in this case the underlying values are very unlikely to change. 

I will make the change shortly - thanks for the feedback.
